shelfzilla/apps/manga/api/urls.py
# coding: utf-8

# third
from rest_framework.routers import DefaultRouter

# own
from .views import VolumesViewSet


router = DefaultRouter(trailing_slash=False)
router.register(r'volumes', VolumesViewSet)
router.register(r'publishers', VolumesViewSet)

urlpatterns = router.urls

shelfzilla/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

from .views import MessagesView


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^messages/$', MessagesView.as_view(), name="contrib.messages"),
    url(r'^$', include('shelfzilla.apps.homepage.urls')),
    url(r'^', include('shelfzilla.apps.landing.urls')),
    url(r'^', include('shelfzilla.apps.account.urls')),
    url(r'^faqs/', include('shelfzilla.apps.faq.urls')),
    url(r'^blog/', include('shelfzilla.apps.blog.urls', namespace='blog')),
    url(r'^series/', include('shelfzilla.apps.manga.urls.series')),
    url(r'^volumes/', include('shelfzilla.apps.manga.urls.volumes')),
    url(r'^publishers/', include('shelfzilla.apps.manga.urls.publishers')),
    url(r'^search/', include('shelfzilla.apps.manga.urls.search')),
    url(r'^_admin/', include('shelfzilla.apps._admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^feedback/',
    #     include('object_feedback.urls', namespace="object_feedback")),
)

# API
urlpatterns += patterns(
    '',
    url(r'^api/v1/', include('shelfzilla.urls_api', namespace='api')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
        (
            r'^files/(?P<path>.*)$',
            'django.views.static.serve',
            {
                'document_root': settings.FILER_STORAGES['public']['main']['OPTIONS']['location']
            }
        ),
        (
            r'^files/thumbnails/(?P<path>.*)$',
            'django.views.static.serve',
            {
                'document_root': settings.FILER_STORAGES['public']['thumbnails']['OPTIONS']['location']
            }
        ),


    )

    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns(
            '',
            url(r'^rosetta/', include('rosetta.urls')),
        )

shelfzilla/apps/manga/models.py
from uuid import uuid4
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db.models.signals import post_save, post_delete
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from filer.fields.image import FilerImageField
from filer.models.foldermodels import Folder

from shelfzilla.models import Model


class Publisher(Model):
    name = models.CharField(_('Name'), max_length=128)
    slug = models.SlugField(_('Slug'), blank=True, null=True)
    url = models.URLField(_('URL'), blank=True, null=True)

    # Cache
    _series = None
    _volumes = None

    def __unicode__(self):
        return u'{}'.format(self.name)

    def get_series_volumes(self, series):
        try:
            series = self.series.get(pk=series.pk)
            return series.volumes.filter(publisher=self)
        except Series.DoesNotExist:
            return []

    def get_absolute_url(self):
        args = [self.pk]
        if self.slug:
            args.append(self.slug)
        return reverse('publishers.detail', args=args)

    @property
    def series(self):
        result = []
        if not self._series:
            queryset = self.volumes.order_by('series__id')\
                .distinct('series').values_list('series')

            result = Series.objects.filter(pk__in=queryset)

            self._series = result
        return self._series

    class Meta:
        ordering = ['name']
        verbose_name = _('Publisher')
        verbose_name_plural = _('Publishers')


class Series(Model):
    SERIES_STATUS = (
        ('open', _('Open')),
        ('finished', _('Finished')),
        ('cancelled', _('Cancelled')),
        ('on-hold', _('On-hold'))
    )

    name = models.CharField(_('Name'), max_length=256)
    slug = models.SlugField(_('Slug'), blank=True, null=True, max_length=256)
    cover = FilerImageField(blank=True, null=True)
    summary = models.TextField(_('Summary'), blank=True, null=True)
    finished = models.BooleanField(_('Finished'), default=False)
    status = models.CharField(_('Status'), choices=SERIES_STATUS,
                              default='open', max_length=16)

    original_publisher = models.ForeignKey(
        Publisher, related_name='original_series', null=True, blank=True)

    art = models.ManyToManyField(
        'Person', related_name='artist_of', null=True, blank=True)
    story = models.ManyToManyField(
        'Person', related_name='scriptwriter_of', null=True, blank=True)

    folder = models.ForeignKey(Folder, null=True, blank=True)

    # Cache
    _languages = None

    def __unicode__(self):
        return u'{}'.format(self.name)

    def have_review_pending(self):
        if self.for_review:
            return True

        for vol in self.volumes.all():
            if vol.for_review:
                return True

        return False

    def get_absolute_url(self):
        args = [self.pk]
        if self.slug:
            args.append(self.slug)
        return reverse('series.detail', args=args)

    def get_status_display_class(self):
        pairs = {
            'open': 'success', 'finished': 'success', 'cancelled': 'danger',
            'on-hold': 'warning'
        }

        return pairs[self.status]

    @property
    def volumes_by_publisher(self):
        return self.volumes.order_by('publisher__name', 'language', 'number')

    @property
    def last_volume_cover(self):
        return self.volumes.filter(cover__isnull=False).last().cover

    def languages(self):
        if not self._languages:
            result = []
            queryset = self.volumes.order_by('language__id')\
                .distinct('language').values_list('language')
            result = Language.objects.filter(pk__in=queryset)

            self._languages = result

        return self._languages

    class Meta:
        ordering = ['name']
        verbose_name = _('Series')
        verbose_name_plural = _('Series')


class SeriesSummary(Model):
    series = models.ForeignKey('Series', related_name='summaries')
    language = models.ForeignKey('Language')
    summary = models.TextField(_('Summary'), null=True, blank=True)

    class Meta:
        unique_together = ('series', 'language', )


class SeriesPublisher(Model):
    series = models.ForeignKey('Series', related_name='publishers')
    publisher = models.ForeignKey('Publisher', related_name='series_published')
    status = models.CharField(_('Status'), choices=Series.SERIES_STATUS,
                              default='open', max_length=16)
    actual_publisher = models.BooleanField(_('Current publisher'),
                                            default=True)

    def get_status_display_class(self):
        pairs = {
            'open': 'success', 'finished': 'success', 'cancelled': 'danger',
            'on-hold': 'warning'
        }

        return pairs[self.status]

    @property
    def volumes(self):
        return self.series.volumes.filter(publisher=self.publisher)


class Volume(Model):
    collection = models.ForeignKey('VolumeCollection', null=True,
        related_name='volumes')
    number = models.IntegerField(_('Number'), null=True, blank=True)
    name = models.CharField(_('Name'), max_length=64, null=True, blank=True)
    series = models.ForeignKey(Series, related_name="volumes")
    publisher = models.ForeignKey(Publisher, related_name="volumes")
    cover = FilerImageField(null=True, blank=True)
    isbn_10 = models.CharField(
        _('ISBN-10'), max_length=10, blank=True, null=True)
    isbn_13 = models.CharField(
        _('ISBN-13'), max_length=13, blank=True, null=True)

    language = models.ForeignKey('Language', null=True)

    retail_price = models.DecimalField(
        _('Retail price'), max_digits=5, decimal_places=2,
        null=True, blank=True)
    pages = models.IntegerField(_('Pages'), null=True, blank=True)
    release_date = models.DateField(_('Release date'), null=True)

    def __unicode__(self):
        if self.name:
            return u'{} {}'.format(self.series.name, self.name)
        elif self.number:
            return u'{} #{}'.format(self.series.name, self.number)
        else:
            return u'{}'.format(self.series.name)

    class Meta:
        ordering = ['series__name', 'language', 'number']
        verbose_name = _('Volume')
        verbose_name_plural = _('Volumes')


class VolumeCollection(Model):
    name = models.CharField(_('Name'), max_length=32)
    series = models.ForeignKey('Series', related_name='collections')
    default = models.BooleanField(_('Default'), default=True)

    def __unicode__(self):
        return u'{} - {}'.format(self.series, self.name)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('Collection')
        verbose_name_plural = _('Collections')


class Person(Model):
    name = models.CharField(_('Name'), max_length=256)
    slug = models.SlugField(_('Slug'), blank=True, null=True)

    def __unicode__(self):
        return u'{}'.format(self.name)

    class Meta:
        ordering = ['name']
        verbose_name = _('Person')
        verbose_name_plural = _('Persons')


class Language(models.Model):
    name = models.CharField(_('Name'), max_length=32)
    code = models.CharField(_('Code'), max_length=5)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('Language')
        verbose_name_plural = _('Languages')


#
# RELATIONS
#
class UserHaveVolume(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='have_volumes')
    volume = models.ForeignKey(Volume, related_name='owned_by')
    date = models.DateTimeField(_('Date'), auto_now_add=True)

    _timeline_message = _('%(volume)s added to collection')
    _event_type = 'have'

    @property
    def event_type(self):
        return self._event_type

    @property
    def timeline_message(self):
        return self._timeline_message % {'volume': self.volume}

    def __unicode__(self):
        return u"{} {} {}".format(
            self.user.username,
            _('have'),
            self.volume
        )

    class Meta:
        ordering = ('volume__series__name', 'volume__number', )


class UserWishlistVolume(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='wishlisted_volumes')
    volume = models.ForeignKey(Volume, related_name='wishlisted_by')
    date = models.DateTimeField(_('Date'), auto_now_add=True)

    _timeline_message = _('%(volume)s wishlisted')
    _event_type = 'wishlist'

    @property
    def event_type(self):
        return self._event_type

    @property
    def timeline_message(self):
        return self._timeline_message % {'volume': self.volume}

    def __unicode__(self):
        return u"{} {} {}".format(
            self.user.username,
            _('wants'),
            self.volume
        )

    class Meta:
        ordering = ('volume__series__name', 'volume__number', )


class UserReadVolume(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='read_volumes')
    volume = models.ForeignKey(Volume, related_name='read_by')
    date = models.DateTimeField(_('Date'), auto_now_add=True)

    _timeline_message = _('%(volume)s marked as read')
    _event_type = 'read'

    @property
    def event_type(self):
        return self._event_type

    @property
    def timeline_message(self):
        return self._timeline_message % {'volume': self.volume}

    def __unicode__(self):
        return u"{} {} {}".format(
            self.user.username,
            _('have read'),
            self.volume
        )

    class Meta:
        ordering = ('volume__series__name', 'volume__number', )


#
# SIGNALS
#
def series_check_filer(sender, instance, created, **kwargs):
    name = instance.name

    # Check folder

shelfzilla/apps/manga/forms.py
# coding: utf-8

# django
from django import forms
from django.utils.translation import ugettext as _

# app
from . import models


class SuggestVolumeForm(forms.ModelForm):
    """
    Form used by users to add a volume that we don't have.
    """
    class Meta:
        model = models.Volume
        fields = (
            'number', 'name',
            'publisher',
            'language',
            'pages',
            'retail_price',
            'isbn_10', 'isbn_13', )
        help_texts = {
            'number': _("The number of this volume."),
            'name': _("Volumes without a number usually have a name instead."),
        }

shelfzilla/apps/manga/api/views.py
# coding: utf-8

# third
from rest_framework import viewsets, filters
from rest_framework.permissions import IsAuthenticated

# own
from .serializers import PublisherSerializer, VolumeSerializer
from ..models import Publisher, Volume


class PublishersViewSet(viewsets.ReadOnlyModelViewSet):
    """
    """
    serializer_class = PublisherSerializer
    queryset = Publisher.objects.filter(hidden=False)
    paginate_by = 20

    filter_backends = (filters.SearchFilter, )
    search_fields = ('name', )


class VolumesViewSet(viewsets.ReadOnlyModelViewSet):
    """
    """
    # permission_classes = (IsAuthenticated,)
    serializer_class = VolumeSerializer
    queryset = Volume.objects.filter(hidden=False)
    paginate_by = 20

    filter_fields = ('series', )
    filter_backends = (filters.SearchFilter,)
    search_fields = ('name', 'number', 'series__name', )

shelfzilla/apps/manga/views/publishers.py
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404

from shelfzilla.views import View
from ..models import Publisher


class PublishersView(View):
    section = 'publishers'


class PublishersListView(PublishersView):
    template = 'manga/publishers/list.html'

    def get(self, request):
        items = Publisher.objects.all()
        context = {
            'items': items
        }
        ctx = RequestContext(request, self.get_context(context))
        return render_to_response(self.template, context_instance=ctx)


class PublishersDetailView(PublishersView):
    template = 'manga/publishers/detail.html'

    def get(self, request, sid, slug=None):
        if slug:
            item = get_object_or_404(Publisher, pk=sid, slug=slug)
        else:
            item = get_object_or_404(Publisher, pk=sid)

        context = {
            'item': item
        }

        ctx = RequestContext(request, self.get_context(context))
        return render_to_response(self.template, context_instance=ctx)

shelfzilla/apps/manga/views/search.py
from django.template import RequestContext
from django import forms
from django.utils.translation import ugettext as _
from django.shortcuts import render_to_response, get_object_or_404

from shelfzilla.views import View
from ..models import Series


class SearchForm(forms.Form):
    q = forms.CharField(max_length=64, label=_('Search'),
                        widget=forms.TextInput(
                            attrs={'placeholder': _('Search')})
    )


class SearchView(View):
    template = 'manga/search.html'
    section = 'search'

    def post(self, request):
        search_query = ''
        items = []
        form = SearchForm(request.POST)

        if form.is_valid():
            search_query = form.cleaned_data['q']

            items = Series.objects.filter(name__icontains=search_query)

        context = {
            'items': items,
            'search_query': search_query
        }
        ctx = RequestContext(request, self.get_context(context))
        return render_to_response(self.template, context_instance=ctx)

shelfzilla/themes/bootflat/templates/manga/series/detail.html
{% extends '_layout.html'|pjax:request %}
{% load i18n staticfiles %}

{% block page_title %}{{ block.super }} | {{ item.name }}{% endblock %}

{% block main_content %}
<div class="container">
    <div class="text-right">
    {% if USER_IS_STAFF and USER_CONFIG.show_admin_links %}
        <a class="btn btn-info" href="{% url 'admin:manga_series_change' item.pk %}">{% trans "Edit in admin" %}</a>
    {% endif %}
    {% if user.is_authenticated %}
        <p>¿No encuentras el tomo que tienes? <a class="btn btn-info" href="{% url 'series.suggest-volume' item.pk item.slug %}">Añádelo a Shelfzila</a></p>
    {% endif %}
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                {% if item.last_volume_cover %}
                <div class="panel-body text-center">
                    <img src="{{ item.last_volume_cover.url }}" class="max-width-80" />
                </div>
                {% endif %}
            </div>
            {% if item.art.count %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Art" %}</h2>
                </div>
                <ul class="list-group">
                    {% for person in item.art.all %}
                    <li class="list-group-item">
                        {{ person.name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% if item.story.count %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Story" %}</h2>
                </div>
                <ul class="list-group">
                    {% for person in item.story.all %}
                    <li class="list-group-item">
                        {{ person.name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Publishers" %}</h2>
                </div>
                <ul class="list-group">
                    {% if item.original_publisher %}
                    <li class="list-group-item">
                        <strong>{% trans "Original publisher" %}:</strong>
                        {% comment %}
                        <a href="{{ publisher.get_absolute_url }}" data-pajax>{{ item.original_publisher.name }}</a>
                        {% endcomment %}
                        <span class="pull-right"><i>{{ item.original_publisher.name }}</i></span>
                    </li>
                    {% endif %}
                    {% if item.publishers.count > 0 %}
                        {% for publisher in item.publishers.all %}
                        <li class="list-group-item">
                            <h4 class="list-group-item-heading">{{ publisher.publisher.name }}</h4>
                            <!--<span class="badge badge-default">{{ publisher.volumes.count }}</span> -->
                            <span class="badge badge-{{ publisher.get_status_display_class }}">{{ publisher.get_status_display }}</span>
                            <div><a href="{{ publisher.publisher.get_absolute_url }}" data-pajax>{% trans "More info" %} &raquo;</a></div>
                        </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1 class="panel-title panel-title-alt text-center">{{ item.name }}</h1>
                </div>
            </div>
            {% if item.summaries.count > 0 %}
            <div class="well well-summary">
            {% for summary in item.summaries.all %}
                {% if item.summaries.count > 1 %}
                <img src="{% static "images/flags/"|add:summary.language.code|add:'.gif' code %}"
                    class="pull-left summary-language" />
                {% endif %}
                {{ summary.summary|linebreaks }}
                <div class="clearfix"></div>
            {% endfor %}
            </div>
            {% endif %}
            <div data-pjax-container="volumes">
                {% block volume_list %}
                <div class="well" id="volume_filters">
                    <form class="form-inline" role="form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="" for="language">
                                {% trans "Language" %}</label>
                            <select name="language" class="form-control">
                                <option value="0">{% trans "All" %}</option>
                                {% for lang in item.languages.all %}
                                <option value="{{ lang.pk }}"
                                    {% if volume_filters.language_id == lang.pk %}
                                    selected="selected"
                                    {% endif %}
                                >{{ lang.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="" for="publisher">
                                {% trans "Publisher" %}</label>
                            <select name="publisher" class="form-control">
                                <option value="0">{% trans "All" %}</option>
                                {% for pub in item.publishers.all %}
                                <option value="{{ pub.publisher.pk }}"
                                    {% if volume_filters.publisher_id == pub.publisher.pk %}
                                    selected="selected"
                                    {% endif %}
                                    >{{ pub.publisher.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="" for="collection">
                                {% trans "Collection" %}</label>
                            <select name="collection" class="form-control">
                                <option value="0">{% trans "All" %}</option>
                                {% for col in item.collections.all %}
                                <option value="{{ col.pk }}"
                                {% if volume_filters.collection_id == col.pk %}
                                    selected="selected"
                                    {% endif %}
                                >{{ col.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">{% trans "Filter" %}</button>
                    </form>
                </div>
                <div class="row">
                    {% for volume in item_volumes %}
                    <div class="col-sm-4">
                        {% include "manga/series/includes/volume.html" with volume=volume user=user show_publisher=True show_details=True show_language=True %}
                    </div>
                    {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

shelfzilla/themes/bootflat/templates/manga/series/suggest_volume.html
{% extends '_layout.html'|pjax:request %}
{% load i18n staticfiles field_tags %}

{% block page_title %}{{ block.super }} | {{ item.name }}{% endblock %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript" src="{% static "bower/select2/dist/js/select2.js" %}"></script>
<script type="text/javascript">
    $(function() {
        $('select').select2();
    });
</script>
{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static "bower/select2/dist/css/select2.css" %}" media="screen" title="no title" charset="utf-8">
{% endblock %}

{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                {% if item.last_volume_cover %}
                <div class="panel-body text-center">
                    <img src="{{ item.last_volume_cover.url }}" class="max-width-80" />
                </div>
                {% endif %}
            </div>
            {% if item.art.count %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Art" %}</h2>
                </div>
                <ul class="list-group">
                    {% for person in item.art.all %}
                    <li class="list-group-item">
                        {{ person.name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% if item.story.count %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Story" %}</h2>
                </div>
                <ul class="list-group">
                    {% for person in item.story.all %}
                    <li class="list-group-item">
                        {{ person.name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">{% trans "Publishers" %}</h2>
                </div>
                <ul class="list-group">
                    {% if item.original_publisher %}
                    <li class="list-group-item">
                        <strong>{% trans "Original publisher" %}:</strong>
                        {% comment %}
                        <a href="{{ publisher.get_absolute_url }}" data-pajax>{{ item.original_publisher.name }}</a>
                        {% endcomment %}
                        <span class="pull-right"><i>{{ item.original_publisher.name }}</i></span>
                    </li>
                    {% endif %}
                    {% if item.publishers.count > 0 %}
                        {% for publisher in item.publishers.all %}
                        <li class="list-group-item">
                            <h4 class="list-group-item-heading">{{ publisher.publisher.name }}</h4>
                            <!--<span class="badge badge-default">{{ publisher.volumes.count }}</span> -->
                            <span class="badge badge-{{ publisher.get_status_display_class }}">{{ publisher.get_status_display }}</span>
                            <div><a href="{{ publisher.publisher.get_absolute_url }}" data-pajax>{% trans "More info" %} &raquo;</a></div>
                        </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1 class="panel-title panel-title-alt text-center">{{ item.name }}</h1>
                </div>
            </div>


            {% if not success %}
            <div>
                <div class="alert alert-info">
                    <p>¡Oooops! ¡Parece que hay un tomo que tú tienes y nosotros no tenemos registrado!</p>
                    <p>Nos harías un gran favor si introduces la información que poseas de dicho tomo aquí para así poder
                        ayudar a otras personas de la comunidad.</p>
                </div>
                <div class="well">
                    <form method="post" class="form">
                        {% csrf_token %}
                        {% for field in form %}
                            {% for error in field.errors %}
                            <p><span class="label label-danger">{{ error|striptags }}</span></p>
                            {% endfor %}
                            <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                                <label class="control-label">{{ field.label }}</label>
                                {{ field|add_class:'form-control' }}
                                {% if field.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">{% trans "Submit for review" %}</button>
                        </div>
                    </form>
                </div>
            </div>
            {% else %}
            <div class="alert alert-success text-center">
                <h4>¡Muchas gracias por colaborar con Shelfzilla!</h4>
                <p>Tu tomo será revisado por nuestro staff para comprobar que los datos son correctos y una vez
                   sea aceptado aparecerá en la web, y podrás añadirlo a tu colección o lista de deseados. ;D</p>
                <a class="btn btn-success" href="{% url 'series.detail' item.pk item.slug %}">Volver a {{ item.name }}</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}